<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="<?php echo $this->getLibPath(); ?>bootstrap-5.2.3-dist/css/bootstrap.min.css">
		<title><?php if (isset($this->title)){ echo $this->title; } ?></title>
    </head>
	<body class="bg-light">
		<main class="container py-5">
            <div class="text-center">
                <h1><?php echo $this->__localization['CONTENT_MANAGEMENT_SYSTEM']; ?></h1>
                <p class="lead"><?php echo $this->__localization['IN_A_SINGLE_STEP']; ?></p>
            </div>

            <div class="py-4">
                <div class="alert alert-success shadow text-center py-4" role="alert">
                    <?php echo $this->__localization['DELETE_INSTALLATION_FILES']; ?>
                </div>
            </div>
        </main>
        <script src="<?php echo $this->getLibPath(); ?>bootstrap-5.2.3-dist/js/bootstrap.bundle.min.js"></script>
    </body>
</html>