            <main class="container-fluid p-5">
                    <?php $this->showMessages(); ?>

                    <small class=""><?php echo $this->__localization['Gallery']; ?> > <?php echo $this->title; ?></small>
                    <h1 class="pb-3"><?php echo $this->title; ?></h1>
                    
                    <form role="form" action="" method="post" enctype="multipart/form-data">
                        <input type="hidden" name="save" value="1">
                        <?php $this->inputHidden('id'); ?>
                        <?php $this->inputHidden('image_file', $this->p_image); ?>
                        <?php $this->inputText('title', $this->__localization['Title'], 'required'); ?>
                        <?php $this->inputSelect('idCategory', $this->__localization['Category'], $this->categories, 'required'); ?>
                        <?php $this->inputFileImage('image', $this->__localization['Image_file'], $this->__localization['Image_file_description']); ?>
                        <div class="pb-3">
                            <div class="form-check">
                                <input name="active" value="1" class="form-check-input" type="checkbox" id="activeCheck"  <?php if ($this->p_active) echo 'checked'; ?>>
                                <label class="form-check-label" for="activeCheck">
                                    <?php echo $this->__localization['ACTIVE_RECORD']; ?>
                                </label>
                            </div>
                        </div>
                        <div class="pb-3 d-none">
                            <label for="translateInputText"><?php echo $this->__localization['LANGUAGE']; ?></label>
                            <select name="language" id="language" class="form-control" id="translateInputText">
                                <option value="es_ES" <?php if ($this->p_language == 'es_ES') echo 'selected'; ?>>Español</option>
                                <option value="en_US" <?php if ($this->p_language == 'en_US') echo 'selected'; ?>>English</option>
                            </select>
                        </div>
                        <div class="pt-3">
                            <button type="submit" class="btn btn-primary btn-lg shadow"><?php echo $this->__localization['SAVE']; ?></button>
                        </div>
                    </form>
                </main>